In [ ]:
import pandas as pd
import numpy as np

Question 1

What's the version of Pandas that you installed?

In [ ]:
pd.__version__

'1.5.3'

In [ ]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-18 08:33:18--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv’

housing.csv         100%[===================>]   1.36M  7.28MB/s    in 0.2s    

2023-09-18 08:33:19 (7.28 MB/s) - ‘housing.csv’ saved [1423529/1423529]



In [ ]:
df = pd.read_csv("/content/housing.csv", encoding="utf-8")
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

Question 2

How many columns are in the dataset?

In [ ]:
df.info() # we can use .info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [ ]:
len(df.columns) # alternatively, we can also use df.columns

10

Question 3

Which columns in the dataset have missing values?

In [ ]:
df.isnull().sum() # will show the number of NaN values in the dataset

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [ ]:
# select only the columns without NaN values
df_notna = df.loc[:, df.notna().all()]

print(df_notna.columns) # columns which doesn't have null value

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'population', 'households', 'median_income', 'median_house_value',
       'ocean_proximity'],
      dtype='object')


Question 4

How many unique values does the ocean_proximity column have?

In [ ]:
len(df.ocean_proximity.unique())

5

Question 5

What's the average value of the median_house_value for the houses located near the bay?

In [ ]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [ ]:
np.average(df.median_house_value)

206855.81690891474

In [ ]:
np.mean(df.median_house_value)

206855.81690891474

In [ ]:
df.median_house_value.sum()/df.median_house_value.count()

206855.81690891474

Question 6

* Calculate the average of total_bedrooms column in the dataset.
* Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
* Now, calculate the average of total_bedrooms again.
* Has it changed?

In [ ]:
np.mean(df.total_bedrooms)

537.8705525375618

In [ ]:
values = {"total_bedrooms": np.average(df.median_house_value)}
df = df.fillna(value=values)
np.mean(df.total_bedrooms)

2607.0476308209954

Question 7
* Select all the options located on islands.
* Select only columns housing_median_age, total_rooms, total_bedrooms.
* Get the underlying NumPy array. Let's call it X.
* Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
* Compute the inverse of XTX.
* Create an array y with values [950, 1300, 800, 1000, 1300].
* Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
* What's the value of the last element of w?

Select only columns housing_median_age, total_rooms, total_bedrooms.

In [ ]:
df1 = df[['housing_median_age','total_rooms', 'total_bedrooms']]

Get the underlying NumPy array. Let's call it X.

In [ ]:
X = df1.to_numpy()
X

array([[  41.,  880.,  129.],
       [  21., 7099., 1106.],
       [  52., 1467.,  190.],
       ...,
       [  17., 2254.,  485.],
       [  18., 1860.,  409.],
       [  16., 2785.,  616.]])

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [ ]:
XT = X.T
XTX = np.matmul(XT,X)
XTX

array([[2.01984850e+07, 1.35332892e+09, 1.53328515e+09],
       [1.35332892e+09, 2.41621366e+11, 1.56209246e+11],
       [1.53328515e+09, 1.56209246e+11, 8.86693048e+12]])

Compute the inverse of XTX.

In [ ]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 7.95608091e-08, -4.41759559e-10, -5.97528980e-12],
       [-4.41759559e-10,  6.63924749e-12, -4.05741848e-14],
       [-5.97528980e-12, -4.05741848e-14,  1.14526655e-13]])

Create an array y with values [950, 1300, 800, 1000, 1300].

In [ ]:
y = [950, 1300, 800]# 1000, 1300]

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [ ]:
XTX_inv_XT = np.matmul(XTX_inv, XT)
# XTX_inv_XT.shape
w = np.matmul(y, XTX_inv_XT)
w[-1]

5.17480654768443e-05